### ISSUE TITLE
Cannot deplay codon framework

### ISSUE THREAD

**Issue by selwynorren** [nabeelio/codon#1]
Hi Nabeel,

I decided to join github and post queries directly here instead of over at phpvms.

I am noticing an error when using the default codon framework. Here is my issue.
1. I am unsure what I need to do in the database (What tables to create)
2. When loading the instance of the testing server is get itself into a terrible loop because the folder core/modules does not exist.
3. Once the folder is created (Nothing inside) I get an error: Fatal error: Call to a member function Set() on a non-object in /opt/lampp/htdocs/xxxxxxxxx/core/classes/Template.class.php on line 71 (Where xxxxx is just the location of my files
4. I corrected this but editing the local.config.php file to include teh database information (I have created the database but have no tables placed yet).
5. Once this is done I get errors that it cannot find teh ezDB.class.php (I can correct this by changing the codon.config.php line 84 to read ezdb/exdb.class.php instead of ezDB.class.php).
6. If i do all of that it returns the error listed on item 3 again.

Could you please point me in a better direction regarding database setup and devployment for first-time use? as well as highlight what that error really means.

I have closed down orrencharters and have moved to alaskan adventures, and since then been writing a few modules, etc but i have not yet deployed codon without the phpvms code itself. I thought instead of coding a whole new site using php, I would rather use your framework for quicker deployment (Makes customization so much easier).

I am currently wanting to use your framework for our church's website but if i want to use it in commercial site, may I purchase licensing from you? what would that price be?

**Comment by nabeelio** [comment]
Hey,

There are some errors, let me see if I can get a basic version working. If you have PHP 5.3 available, I have been using mostly this: https://github.com/nshahzad/liteframe

As for purchasing, licensing, there is no cost, it's MIT license to modify as you see fit. I have to see if I have a newer copy of Codon which I haven't pushed up.

**Comment by nabeelio** [comment]
Also, the database tables, etc, you have to create as you see fit for your application, same with the Data classes. That all depends on your app. (how phpVMS is designed)

Though I've moved on to liteframe, which uses php-activerecord as the database layer.

**Comment by selwynorren** [comment]
Hey Nabeel,

Thanks so much for responding, OK Ill give liteframe a try, I have only recently become more acquainted with phpvms so I felt more comfortable with that framework.

So to confirm codon does not need predefined tables holding any data to start off with, I can create as what I need when I need it, along with the appropriate data classes.

**Comment by selwynorren** [comment]
I have just checked and I dont have 5.3 available, I only have 5.2 available, will this make a difference?

**Comment by nabeelio** [comment]
Yeah, it's 5.3 only. They're essentially the same style coding, just some changes.

And right, there are no predefined tables or anything. You create everything in the same style as phpVMS. I'm tracking down a clean copy, it's on some server, somewhere. If not, I will fix this copy up that's on there now

**Comment by selwynorren** [comment]
Thanks so much Nabeel, ill look forward to hearing from you

**Comment by selwynorren** [comment]
Hey Nabeel,

I just wanted to follow up on that tracking down of the codon files you spoke of?

**Comment by nabeelio** [comment]
I just committed a newer copy, give that a shot

**Comment by selwynorren** [comment]
Thanks so much, ill post shortly

**Comment by selwynorren** [comment]
Hey NAbeel

OK I have it installed. Unfortunatly its not working yetm but this time some different errors. The steps taken.
1. Copied files to xampp server.
2. Edited core/local.config.php
3. changed line 84 of codon.config.php to reflect correct location of exdb class (Two errors appear at this stage:
   Warning: require(/opt/lampp/htdocs/clients/highwaychurch/core/classes/ezDB.class.php) [function.require]: failed to open stream: No such file or directory in /opt/lampp/htdocs/xxxxxxxxxx/core/codon.config.php on line 84

Fatal error: require() [function.require]: Failed opening required '/opt/lampp/htdocs/clients/highwaychurch/core/classes/ezDB.class.php' (include_path='.:/opt/lampp/lib/php') in /opt/lampp/htdocs/xxxxxxxxxx/core/codon.config.php on line 84
3a. the line stipulates: require CLASS_PATH.DS.'ezDB.class.php'; 
3b changed to: require CLASS_PATH.DS.'ezdb/ezdb.class.php';
4. Once the site is refreshed all hell breaks loose It starts with this error:
Warning: opendir(CODON_MODULES_PATH) [function.opendir]: failed to open dir: No such file or directory in /opt/lampp/htdocs/xxxxxxxxx/core/classes/MainController.class.php on line 68

After that it loops indefinite with the following error:
Warning: readdir() expects parameter 1 to be resource, boolean given in /opt/lampp/htdocs/xxxxxxxxxxx/core/classes/MainController.class.php on line 70

I have created te modules folder as well as a Modules folder, I even had the folders there as well as gone again, nothing changes this error. and I really do mean an infinite loop, It crashes the whole browser if left untended lol

I hope some of this helps

**Comment by nabeelio** [comment]
Ok, hmm, let me try something else... gimme a day or two, if that's ok?

**Comment by selwynorren** [comment]
Yeah sure, take your time. I might have it all sorted as well, I managed to get a hybrid thing going between installing a beta vms system and copying certain files over. Don't hold your breathe lol I am no wizard at all. If I succeed I can send you the file I did, maybe you can give them a once over and check it all good?

But I would rather you get it sorted as I could only do mare damage than harm with my knowledge lol

**Comment by nabeelio** [comment]
I realized it needs to settings table from phpVMS, though I think the only setting is CURRENT_SKIN, which i've added to app.config/local.config. Try giving the one there a shot now, I synced it from the latest phpVMS. I didn't get to fully test it, if it's a no go, I will run through it again tonight or tomorrow when I have more than a few minutes

**Comment by selwynorren** [comment]
Thanks so much for all your help, Ill test it now quick and take a peek at it.

**Comment by selwynorren** [comment]
Its looking really good,

I picked up on the fact it needs the database setti9ngs table. I have used your new code now and its almost perfect. Its fully functional with some mods made. details below:
1. copy files to local server without any modification to any files (Sterile Enviroment)
2. Requires that I copy the SiteData class to be available (I copied this from teh phpvms files
3. Requires I copy over SettingsData Class
4. then it requires me to have the database details set up in the local.config.php file
5. I filled those details in
6. Required Aith Class
7. requires cron class
8. requires FinanceData Class
9. This is when I paid attention to teh fact it was teh bootstrap.in.php file making all these requirements
   10 I edited teh bootstrat file and removed teh following lines only:
   
   ```
   if(Config::Get('PILOT_AUTO_RETIRE') == true)
   {
       $within_timelimit = CronData::check_hoursdiff('find_retired_pilots', '24');
       if($within_timelimit == false)
       {
           PilotData::findRetiredPilots();
           CronData::set_lastupdate('find_retired_pilots');
       }
   }
   
   if(Config::Get('CLOSE_BIDS_AFTER_EXPIRE') === false)
   {
       $within_timelimit = CronData::check_hoursdiff('check_expired_bids', '24');
       if($within_timelimit == false)
       {
           SchedulesData::deleteExpiredBids();
           CronData::set_lastupdate('check_expired_bids');
       }
   }
   
   /* Expenses, make sure they're all populated */
   $within_timelimit = CronData::check_hoursdiff('populate_expenses', 18);
   if($within_timelimit === false)
   {
       FinanceData::updateAllExpenses();
       CronData::set_lastupdate('populate_expenses');
   }
   ```

With all of that removed I have a functional site (Well Kind of)

It complains that no modules were found (This is a good error to have)
It also complains that the core_navigation file is missing (This just comes from the template itself)
and Finally complains that it cannot find the frontpage module.

Everything else works perfectly. What I can do if you want to, is mod the template slightly, change the logo, create a simplistic menu, put in the front page module (This will solve the module missing errors).

I can then email it to you or upload it somewhere for you to check that I have not messed some code somewhere

Again thanks for all your help

**Comment by selwynorren** [comment]
Me again,

Just to let you know I created a table for settings which just contained teh basic stuff, sql dump to follow:

## -- Table structure for table `ca_settings`

DROP TABLE IF EXISTS `ca_settings`;
CREATE TABLE IF NOT EXISTS `ca_settings` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `friendlyname` varchar(25) COLLATE utf8_unicode_ci NOT NULL DEFAULT '',
  `name` varchar(25) COLLATE utf8_unicode_ci NOT NULL DEFAULT '',
  `value` varchar(150) COLLATE utf8_unicode_ci NOT NULL DEFAULT '',
  `descrip` varchar(150) COLLATE utf8_unicode_ci NOT NULL DEFAULT '',
  `core` smallint(6) NOT NULL DEFAULT '1',
  PRIMARY KEY (`id`),
  UNIQUE KEY `name` (`name`)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci AUTO_INCREMENT=6 ;

## 

## -- Dumping data for table `ca_settings`

INSERT INTO `ca_settings` (`id`, `friendlyname`, `name`, `value`, `descrip`, `core`) VALUES
(1, 'Website Name', 'SITE_NAME', '', 'The name of your site. This will show up in the browser title bar.', 1),
(2, 'Webmaster Email Address', 'ADMIN_EMAIL', '', 'This is the email address that email will get sent to/from', 1),
(3, 'Date Format', 'DATE_FORMAT', 'd/m/Y', 'This is the date format to be used around the site.', 1),
(4, 'Current Skin', 'CURRENT_SKIN', 'crystal', 'Available skins', 1),
(5, 'Default User Group', 'DEFAULT_GROUP', '2', 'This is the default group if they are not explicitly denied', 1);

Then I changed the local.config file as follows:

<?php

/**
- This is the phpVMS Main Configuration File
  *
- You can add any additional modules at the bottom
- This file won't be modified/touched by future versions
- of phpVMS, you can change your settings here
  *
  */
  define('DBASE_USER', '');
  define('DBASE_PASS', '');
  define('DBASE_NAME', '');
  define('DBASE_SERVER', 'localhost');
  define('DBASE_TYPE', 'mysql');

define('TABLE_PREFIX', 'ca_');

define('SITE_URL', '');

# Page encoding options

Config::Set('PAGE_ENCODING', 'ISO-8859-1');

# Maintenance mode - this disables the site to non-admins

Config::Set('MAINTENANCE_MODE', false);
Config::Set('MAINTENANCE_MESSAGE', 'We are currently down for maintenance, please check back soon.');

# See more details about these in the docs

Config::Set('PAGE_EXT', '.htm');    # .htm is fine. You can still run PHP

Obviously all the fields were filled in accordingly. and voila everything is fully functional for the codon framework.

I have no idea how to build the installer to install codon like you have in the vms version, but maybe something similar just to be able to input that basic information would be good.

P.S Please excuse my really bad spelling, its normally really bad and get totally worse when i get excited lol

**Comment by nabeelio** [comment]
Hey - ok I commited another copy removing all the dependencies - including the settings table. The bootstrap file is complete barebones now too.

The only real setting you'd need is CURRENT_SKIN, which is now  Config::Set() call

**Comment by selwynorren** [comment]
Hey NAbeel,

Awesome, Ill download it now and use it. Once I have done my site I will send you a link as it will be based entirely on the codon framework.

a current sample of the template can been seen here:
http://www.chiselledatom.co.za/clients/highwaychurch

Chat soon again
